### ISSUE TITLE
Throughput Entry frequently trips first time users

### ISSUE THREAD

**Issue by royreddy** [FocusedObjective/FocusedObjective.Resources#35]
on the [Forecast] sheet,  **#4. Throughput**  has both an Entry Dropdown for (Weeks) and a Display for | nn| days.  the Dropdown does not show the selector until you select the cell.
In the last few months I have seen several people , including myself, enter the Days and fUbar the overall calculations.  One debate was is this workdays or duration? omg.
Once this happens the entire sheet can go south and the recovery is start again! or maybe download another copy if it has been saved.

I suggest make the Display for |  nn| days much more clearly a Display only screen element.  
Ideas are;
a. change the colour to Black or Grey.  orange makes it the same colour as the other Entry fields.
b. separate it with greater distance from the Dropdown box
c. add a comment to reinforce that Days are display
d. prefix the display with |= calculated  nn| days
e. or remove the Display, maybe it is just distracting. once selected the Dropdown show Sprint duration.

thanks very much for your Focussed _contributions_.
cheers!  RrR

**Comment by FocusedObjective** [comment]
Thanks. I've made the following changes.

1. Made the days calculation light grey
2. Added an alert box when you enter that cell
3. Added a drop-down combo box image to the week/sprint selector so hat it is always shown. A hack I know, but hopefully it will make it clearer that it is a drop-down before people select that cell

Love your feedback if this solves the issue

Troy

**Comment by royreddy** [comment]
! Made the days calculation light grey
Looks Good

! Added an alert box when you enter that cell
Works well

! Added a drop-down combo box image to the week/sprint selector so hat it is always shown. A hack I know, but hopefully it will make it clearer that it is a drop-down before people select that cell

I have mixed feelings about this. On the one hand it communicates that there is a dropdown. But when I select the item, it is just a graphic object and so it feels in the way.
> Love your feedback if this solves the issue
Yes Love the dialog, hope it solves the issue.  Time will tell.

**Comment by royreddy** [comment]
Two more suggestions.
1. Amend the Duration name  Sprint (1 week) < So that it follows the same template as the 2,3,4 week choices
This actually reads better on the Forecast page the first time it is Opened
1a. Could the 2 week selection be save as the default?

2.  It is regrettable that the Dropdown does not look like a dropdown until the cell is selected.(Excel limit)  
What about loose the graphic,  Change the Borders to make the cell look more like a dropdown?
(image attached)

![forecaster dropdown capture](https://cloud.githubusercontent.com/assets/6502124/26634062/655dfd6e-45e3-11e7-88c5-576173bb262d.PNG)

**Comment by FocusedObjective** [comment]
Thanks Roy. I took another shot at it.

1. I didn't want to use the word sprint. I tend to use double the pace of the sprint as my measurement unit. The shortest period that non-zero values occur. So, i compromised. I used weeks in all cases. Was the word sprint important to you?

1a. You can choose the default in your downloaded copy and save that. I also made the "Settings" worksheet unbidden where all of the selections are listed. You can alter the wording there to match your companies needs.

2. OK. loved the idea of the border change. I also added more descriptive text under the combo box cell

Download the latest and love your feedback.

Troy.
