### ISSUE TITLE
Request: no more IFNA

### ISSUE THREAD

**Issue by lunivore** [FocusedObjective/FocusedObjective.Resources#36]
Hi Troy, the IFNA formula (Montecarlo sheet column B, "Throughput Forecaster") isn't supported by older versions of Excel, so it results in a #NAME error. Any chance we can get rid of it and use something else, since it's the only thing causing an issue? I am happy to test and have an Office & Business version of Excel 2010.

**Comment by FocusedObjective** [comment]
OK. I've made  fix I think. Apologies, sometimes i get a rush of blood and use a newer formula.

If you could give it a check i'd appreciate it. 

https://github.com/FocusedObjective/FocusedObjective.Resources/blob/master/Spreadsheets/Throughput%20Forecaster.xlsx

**Comment by lunivore** [comment]
Fantastic, that works! Thanks Troy!
